<!--
  GENERATED by cognition-os-toolkit/init.py.

  Modules included: deploy-surface.md, ci-gate-governance.md

  BEFORE COMMITTING THIS FILE:
    1. Rename it to CLAUDE.md (drop the .generated suffix) once you've
       reviewed it - this name is deliberately non-final so it never
       silently overwrites a hand-written CLAUDE.md you already have.
    2. Fill in every placeholder token (anything in <ANGLE_BRACKETS>,
       e.g. <DEPLOY_HOST>, <APP_DIR>) with your project's real facts -
       see PROJECT_FACTS.yml (copy PROJECT_FACTS.template.yml first).
    3. Re-read CLAUDE-MD/ASSEMBLE.md in the toolkit for the
       recommended concatenation-vs-include-comment tradeoff and for
       guidance on splitting your OWN project-specific rules into
       further modules as they accumulate.
-->

# Project Operating Rules — CORE

This file is auto-loaded into every agent session in this repo. It contains
load-bearing operational discipline that a session must not re-discover from
scratch. These rules apply to any serious multi-session or multi-agent
codebase, regardless of domain. Optional, infrastructure-specific rules live
in `modules/` — see `ASSEMBLE.md` for how to compose them into a full
`CLAUDE.md`.

---

## Single-writer / worktree-isolation discipline

Two agents (or two sessions) writing to the **same** working tree at the same
time cross-contaminates branches — a commit meant for one line of work lands
on another, unrelated branch, mid-edit.

**Why:** in a concurrent-agent workflow, one session's checkout is a shared,
mutable resource. If a second session checks out or commits in that same
directory while the first is mid-task, the two histories interleave: a
commit intended for branch A can land on branch B, or a half-finished edit
from one task gets swept into another task's commit. Recovering from this
requires reconstructing which commit belongs where and force-pushing a
corrected history — expensive, and risky if done carelessly.

**How to apply:**
1. **One active writer per working tree.** Do not run two agents that both
   `checkout` / commit in the same working directory at the same time. Treat
   the primary checkout as single-writer.
2. **Each concurrent track gets its own worktree.** Any high-risk or
   long-running parallel track (a feature branch, a migration, a deploy
   prep, a research spike) should get `git worktree add -b <branch>
   ../<repo>-wt-<task> origin/<default-branch>`, do its work there, then
   `git worktree remove` when done. Never let two independent tasks share
   one mutable tree.
3. **Force-push recovery requires an evidence receipt.** If a history
   correction (force-push, rebase surgery) is ever necessary, the
   commit/PR body documenting it must include: the old branch head, the
   commit that was dropped/moved, proof the dropped commit is preserved on
   its correct branch (e.g. identical patch-id), the new head, and a
   `diff --name-only` scope proof. Always use `--force-with-lease` (never a
   bare `--force`) so a concurrent push fails the lease check instead of
   silently clobbering data.
4. **Scope-gate every PR before merge.** `diff --name-only` against the
   merge base must contain *only* the files the PR's task owns. A foreign
   file or an unrelated commit — even if CI is green — fails review. The
   merge unit must be scoped, explainable, and auditable.

---

## Red-gate repair protocol

If a CI gate is **already red from a cause unrelated to your current change**
(discovered while trying to merge or sync something else), do not silently
fix it inline and do not merge over it.

**Why:** an already-red gate is often a symptom of a different, possibly
larger, problem than the one you're currently solving. Quietly patching it as
a side-effect of an unrelated PR hides the failure's real scope, skips
review of the fix itself, and risks conflating two unrelated changes in one
diff. The instinct to "just fix it while I'm in here" is exactly how small,
unreviewed hotfixes accumulate into an undocumented pile of exceptions.

**How to apply.** Choose ONE of three explicit paths, in this order of
preference:

1. **PAUSE** — stop and report the red gate to whoever owns the repo.
   Default for anything non-trivial, ambiguous, or touching code you don't
   fully understand.
2. **SMALL HOTFIX PR** — open a dedicated, narrowly-scoped PR for the fix
   only. Preferred when the fix is clear but not an emergency. Keeps the
   review trail and does not entangle the fix with whatever you were
   originally doing.
3. **EMERGENCY DIRECT-TO-MAIN COMMIT** — only when the red gate is blocking
   a time-sensitive operation AND the fix is unambiguous (e.g. an
   established exclusion-list pattern). If used, the commit message MUST be
   a receipt containing: `reason` (why the default branch was red) ·
   `scope` (exactly what changed) · `local reproduction` (the command +
   output proving the failure) · `post-fix check` (the command + output
   proving green) · `why no PR` (why a hotfix PR was not used instead).

**Do not normalize path 3.** Direct-to-main code fixes are an exception
path, not a pattern. Documentation-only additions are not "code fixes" and
are out of scope for this rule.

### Known-transient CI patterns

Some red checks are **infra blips, not findings**. Before treating a red
gate as real, fetch the actual job log and match against a maintained list
of known-transient signatures — on a match, **re-run the job; do not
re-diagnose or touch code**:

- A check failing at the checkout/auth step with an authentication or
  credential-prompt error → checkout-auth transient; the actual job never
  ran.
- `Connection timed out`, `unable to access … 5xx`, or TLS handshake errors
  → network transient.
- A docs-only or path-filtered change showing "no relevant checks ran" while
  the merge-readiness status is otherwise clean → the CI config correctly
  skipped irrelevant jobs; that is not a failure.

Maintain this list as your project's own known-transient patterns accumulate
(see `red-gate` workflow if your toolkit includes one). If a red check does
NOT match a known-transient pattern, treat it as real and apply the protocol
above. **Never merge over an unclassified red check.**

---

## Gate-collapse prevention — never silently drop a CI gate

If your CI gate surface is defined across **more than one coupled
file/surface** (e.g. a local-CI runner script, a CI workflow file, and a
parity-checking script that cross-validates the two), two PRs that both edit
these files in parallel create a standing risk: the PR that merges **second**
is based on a pre-merge version of the default branch, and its
rebase/merge can silently overwrite the shared region — deleting a gate the
first PR added, with no individual check catching the loss (a naive parity
checker can stay green with one fewer gate on all sides, and a checker that
looks at file-shape rather than gate-identity won't notice a job renamed out
of existence).

**Why:** parity between two files only proves the files agree with each
other, not that a diff didn't drop the same line from all of them
simultaneously. A rebase or merge that touches the shared region is exactly
where that failure mode hides.

**How to apply:** if two changes both touch your gate-definition surfaces,
confirm — after every rebase — that BOTH the gate being added and every
pre-existing gate are still present across all coupled surfaces. Treat this
as a standing risk to watch for manually until a structural fix is in place.
If your project has scheduled-pipeline or CI infrastructure worth the
investment, see `modules/ci-gate-governance.md` for the structural fix: a
single source-of-truth `gates.yml` plus a guard script that diffs the gate
set on a branch against the default branch and fails on any unexplained
removal.

---

## Documentation progress vs runtime progress

When evaluating "what changed," "what can this system do now," or whether a
capability is live, distinguish **five** states explicitly. Conflating any
two of them produces normalized false confidence.

| State | What it means |
|---|---|
| **RUNTIME-ACTIVE** | Code is executing right now in the live system (a running process, a scheduled job, a deployed service). Name the runtime path. |
| **CODE-LANDED, NOT RUNTIME-ACTIVE** | Present on the default branch, but nothing has deployed/rebuilt/restarted the thing that would run it. |
| **DOCUMENTED, NOT EXECUTED** | A plan, migration, or one-time action is approved and written down; the mutation itself has not happened. |
| **DOCUMENTED, NOT ENFORCED** | A design doc, contract, or policy exists and is accepted; no code path actually checks or honors it yet. |
| **DOC-ONLY** | A diagnosis, write-up, or issue has been filed; the underlying fix or producer change has not started. |

**The risk is normalization** — mistaking documentation progress for runtime
progress. A PR merging to the default branch does **not** itself change
what's running in production. A design doc being accepted does **not**
itself enforce anything. An issue being filed is the diagnostic step; it is
not the fix.

**Forbidden assertions:**

- Citing a merged PR as "live" or "protecting production" when nothing has
  deployed, rebuilt, or restarted the thing that would run it.
- Citing an accepted design doc / ADR / contract as "enforced" when no code
  path actually honors it.
- Citing a filed issue as "fixed" when only the diagnosis has landed.
- Citing a planned data correction or backfill as "complete" when only the
  plan has merged.
- Describing a week's (or sprint's) progress by counting merged PRs rather
  than by naming the runtime paths newly activated.

**When asserting that a capability is live, name the runtime path.** Which
process is running the code (and how do you know — a version marker, a
health check, a log line). Which scheduler entry or trigger invokes it.
Which observable side effect (a row written, an event emitted, a metric
updated) can be pointed to as proof. **If you can't name the runtime path,
the capability is not live — it is only documented.**

**Absence of failure events is not evidence of success.** Zero alerts or
zero failure-log rows could mean the thing is running healthy, or it could
mean the check that would produce those rows isn't running at all. Check the
runtime, not just the failure surface.

---

## Evidence-first / evidence-freshness contract

Do not recommend an action that touches live or runtime state — a deploy, a
database write, an incident closure, a configuration change — until you
have pulled the relevant live evidence, or until you explicitly state that
evidence is stale or unavailable.

Every such recommendation must declare one of three evidence states:

- **`EVIDENCE_CURRENT`** — live evidence pulled in this session, recent
  enough for the decision. Proceed normally.
- **`EVIDENCE_STALE`** — evidence exists but predates a recent change, or
  was pulled earlier in a longer session. Disclose the staleness; do not
  recommend high-mutation actions (deploy, DB write, incident close) from
  it.
- **`EVIDENCE_UNAVAILABLE`** — the tools needed to check are absent or
  unreachable, or the session predates a relevant change and can't see it.
  Disclose why. Proceed only for pure design/planning work that makes no
  claim about current runtime state.

### Evidence freshness before filing a recurrence

Before reopening a closed issue, or filing a new occurrence of a previously
fixed problem, based on local observation, prove all of:

| Claim | Proof |
|---|---|
| local checkout is current | the local branch has no unmerged commits behind the remote default branch (or the gap is acknowledged) |
| the remote default branch is fresh | you fetched it in this session |
| the failure reproduces against current remote state | re-run from a fresh checkout of the remote default branch reproduces it, or you explicitly name the artifact source you tested against |

If the failure did **not** reproduce against current remote state (e.g. it
was a stale local checkout running pre-fix code), the observation is **not**
a recurrence — it is a **stale-evidence phantom**. Log it as a note on the
existing issue ("phantom from stale checkout of `<commit>`, fix already
present in `<PR/commit>`") and do **not** increment any recurrence counter.

---

## Check for existing work before opening a duplicate deliverable

Before opening a PR or issue for a **named, single-instance deliverable**
(an acceptance receipt, a migration apply-receipt, an incident write-up, a
one-time design doc), check whether a concurrent session has already opened
it:

```
# Search open PRs/issues by keyword
<vcs-cli> pr list --state open --search "<deliverable keyword>"
<vcs-cli> issue list --state open --search "<deliverable keyword>"

# Check remote branches by keyword
git ls-remote --heads origin | grep -i <keyword>
```

If one exists: **do not open a duplicate.** Review it, independently verify
its claims, then either approve/merge it (if authorized and green) or
comment on it. A second PR for the same deliverable forks the evidence
trail and wastes review effort.

This applies doubly under multi-agent or concurrent-session use, where two
independent sessions are statistically likely to pick up the same obvious
next deliverable at the same time.

---

## Ops-lease convention for live shared-state mutations

Before touching any live, shared, mutable surface — a remote host's
crontab, a shared configuration file, a policy registry, a persistent
memory/notes file that multiple sessions read and write — acquire an
advisory lease first.

**Why:** two parallel sessions independently preparing the same edit to a
shared mutable surface is a real, observed failure mode in concurrent-agent
workflows, not a hypothetical. Without a lease, both sessions can compute a
correct-looking diff against the state they each saw, and the second one to
apply silently overwrites the first's work — even though neither session did
anything wrong in isolation.

**How to apply:**
1. Check for competing leases (a lock-file directory, a shared "who owns
   what" board) before starting.
2. Capture a pre-image hash of the target surface.
3. Write a lock file recording: owner, purpose, pre-image hash, expiry.
4. Immediately before applying the mutation, re-verify the hash against the
   pre-image — abort and release the lease if it changed.
5. Apply the change, verify it landed correctly, release the lease.

Treat this as mandatory for any surface more than one active session can
reach — not just remote infrastructure. A shared memory file that multiple
agents append to has the same collision risk as a remote crontab.

---

## Control-safety for automated remediation / watchdogs

Any automated loop that can **restart, disable, delete, or mutate a live
service** must document — before it is allowed to act — all four of:

1. **Sensor proof** — the exact signal it uses to decide the service is
   unhealthy, and explicitly what that signal does **not** prove. (A signal
   that only proves "a socket answered" is not proof that "the service is
   doing its job.")
2. **Actuator** — the action it may take, and the one specific failure mode
   that action actually fixes.
3. **Cooldown / max-attempt rule** — minimum spacing between actions and a
   hard cap on repeated attempts.
4. **Stop condition** — the point at which it must stop acting and alert a
   human for intervention, instead of acting again.

**Invariant: a strong actuator paired with a weak or ambiguous sensor is
unsafe.** Ambiguous or inconclusive sensor states must cause the loop to
alert-or-hold — never to repeatedly actuate. A monitor must never be able to
harm a healthy service indefinitely just because its sensor can't tell
healthy from unhealthy.

See `modules/automated-remediation.md` for a fill-in-the-blank template to
apply this to each of your project's own watchdogs.

---

## Temporal grounding

Never compute day-of-week, "is this stale," or "did this run on schedule"
from mental arithmetic on a bare date string. Use an authoritative
tool/hook output instead.

**Why:** date-number-to-day-of-week arithmetic (and calendar-day-delta
arithmetic in general) is a class of error that looks trivial and is not —
agents reliably get it wrong under time pressure, and the failure is silent
(a plausible-sounding wrong day, not a crash). The fix is procedural, not
"be more careful": always defer to a tool that actually knows the calendar.

**How to apply:**
- Before any date-sensitive reasoning (staleness checks, "did this run on
  schedule," gap detection), call an authoritative date/calendar utility
  rather than reasoning about the date string yourself.
- Never use a bare `(now - last_timestamp).days` computation for staleness
  claims without going through a calendar-aware helper — plain elapsed-time
  arithmetic silently miscounts across weekends, holidays, or any
  non-trading/non-business period your project cares about.
- If your project has domain-specific non-trading-days, holidays, or
  business-hour semantics, see `modules/business-calendar.md` for a
  pluggable domain-calendar extension. This CORE rule is deliberately
  domain-agnostic — "use an authoritative clock/calendar tool" holds even
  for projects with no business-calendar concept at all (e.g. just "don't
  hand-compute day-of-week").

---

## Memory-freshness discipline

A memory record that names a specific function, file, flag, or table is a
claim that it existed **at the time the note was written** — not a
guarantee it still does. Before acting on a memory note, verify the claim
still holds (the file exists, the function is still defined, the flag is
still read somewhere) rather than trusting the note at face value.

**Why:** memory files are meant to survive across many sessions, but the
codebase they describe keeps changing underneath them. A note that was
perfectly accurate when written can silently go stale — the function got
renamed, the file got deleted, the flag got removed in a refactor — and
nothing marks the note as invalid. Acting on a stale memory note produces
confidently wrong recommendations that reference things that no longer
exist.

**How to apply:**
- Before recommending an action based on a memory note that names a
  specific code artifact, spot-check that the artifact still exists (a
  quick file/symbol search) rather than assuming the note is current.
- If your project has a memory-consolidation or decay-checking tool, prefer
  it — an automated decay-checker that periodically re-verifies memory
  claims against the current codebase is strictly better than leaving this
  to manual discipline every time a note is read. Treat "verify before
  trusting" as the fallback for projects that don't yet have that
  automation, not as the permanent state to settle for.


---


# Module: Deploy Surface

**Include this module if:** your project deploys to a remote host — a VPS,
a bare-metal server, a cloud VM, or any long-lived remote machine you SSH
into or otherwise administer directly (this module is less relevant if you
only deploy via a fully-managed PaaS with no host-level access; adapt the
"two runtime identities" and "read-only deploy key" sections if so).

Fill in the placeholder tokens below with your project's actual facts, then
delete this instructional preamble.

---

## Deploy surface — canonical facts

| Token | Meaning | Your value |
|---|---|---|
| `<DEPLOY_HOST>` | Primary reachable address (IP or hostname) of the deploy target | _fill in_ |
| `<DEPLOY_HOST_ALT>` | Secondary/overlay-network address, if one exists (e.g. a private VPN/mesh address that bypasses public-IP rate limits) | _fill in, or delete row_ |
| `<DEPLOY_USER>` | The **non-root** account used for all access | _fill in_ |
| `<APP_DIR>` | Absolute path to the application on the deploy host | _fill in_ |
| `<SECRET_PATH>` | Where runtime secrets live on the deploy host | _fill in_ |
| `<CONTAINER_OR_SERVICE_NAME>` | Name of the primary running container/service, if containerized | _fill in_ |

**Common access patterns** (adapt the actual command to your stack):

```bash
# Run a one-off command on the host:
ssh <DEPLOY_USER>@<DEPLOY_HOST> '<command>'

# Copy a file off the deploy host:
scp <DEPLOY_USER>@<DEPLOY_HOST>:<APP_DIR>/<path> .

# Copy a file onto the deploy host:
scp ./<file> <DEPLOY_USER>@<DEPLOY_HOST>:<APP_DIR>/
```

---

## Never use the root/superuser account

**Always use the designated deploy/sudoer account. Never `root@` (or
equivalent superuser login).**

**Why:** a dedicated deploy account that holds exactly the sudo rights it
needs, with root login disabled entirely, means a compromised or
mistake-prone session can't accidentally do host-wide damage — the blast
radius of any single command is bounded by what that account can do, not by
what root can do. It also means there is exactly one account with a key on
file to audit, instead of an ambiguous "whoever has the root key" surface.

**How to apply:**
- Any command, script, or runbook example that shows a superuser login
  (`root@<host>` or equivalent) is a bug — fix it to use `<DEPLOY_USER>@`.
- If a historical or archived document (a postmortem, an old incident
  write-up) references superuser login, that reference is preserved for
  record-keeping only — do not copy commands from it verbatim into current
  work.

---

## Two runtime identities can look like one system

If your deploy surface runs **more than one distinct runtime component**
against the same codebase — e.g. a host-level agent/daemon process that
execs directly from a git checkout, alongside a fully containerized
application that's rebuilt from an image — confirm **which one you are
actually redeploying** before restarting or rebuilding anything. The two
can share a repository and even share a directory, while having completely
independent deploy actions, version markers, and blast radii.

**Why:** conflating the two is how an unrelated maintenance action ends up
restarting a live, order-sensitive, or otherwise expensive-to-restart
service. A change meant only for a lightweight host-level helper process can
accidentally trigger a full container rebuild (or vice versa) if the two
runtime identities aren't kept explicitly distinct in your own mental model
and documentation.

**How to apply:**
1. Maintain a small table (in your own deploy docs) mapping each runtime
   component to: what process/container runs it, where its code comes from
   (host git checkout vs baked-into-image), what the deploy action is for
   that component specifically, and what the restart blast radius is.
2. Before deploying, identify which row of that table your change belongs
   to. A host-level process update is usually a simple `git pull` on the
   host with **no rebuild**. A containerized-app update usually requires a
   full image rebuild and container recreation.
3. The two components' version markers (e.g. host git HEAD vs. a baked-in
   commit SHA inside a container) may legitimately differ at any given
   time — that is not automatically drift, it's two independent deploy
   cadences. Verify each component's health on its own terms, not by
   comparing the two SHAs to each other.
4. A rollback of one component (e.g. `git reset --hard <previous_sha>` on
   the host) does not touch the other component at all — confirm that's
   what you intend.

---

## Read-only deploy-key discipline

If the deploy key installed on the remote host is **read-only** (can pull
but cannot push), `git push` from the host will fail with a permission
error. This is a deliberate security posture, not a bug — but it means any
commits made directly on the host (forensics scripts, incident notes,
one-off diagnostic commits) need an explicit workflow to reach your primary
remote.

**Bundle-and-fetch workflow:**

```bash
# Step 1 — on the deploy host: bundle commits not yet on the remote default branch
ssh <DEPLOY_USER>@<DEPLOY_HOST> 'cd <APP_DIR> && git bundle create /tmp/research.bundle origin/<default-branch>..HEAD'

# Step 2 — copy the bundle to your local machine
scp <DEPLOY_USER>@<DEPLOY_HOST>:/tmp/research.bundle .

# Step 3 — on your local machine: register the bundle as a remote and fetch
git remote add host-bundle ./research.bundle   # only needed once per session
git fetch host-bundle

# Step 4 — push the fetched commits to your primary remote (which has write access)
git push origin <branch>

# Step 5 — clean up
git remote remove host-bundle
rm research.bundle
ssh <DEPLOY_USER>@<DEPLOY_HOST> 'rm /tmp/research.bundle'
```

**When this applies:** any session that creates commits directly on the
deploy host. Check for divergence first:

```bash
ssh <DEPLOY_USER>@<DEPLOY_HOST> 'cd <APP_DIR> && git status'
ssh <DEPLOY_USER>@<DEPLOY_HOST> 'cd <APP_DIR> && git log --oneline origin/<default-branch>..HEAD'
```

If the second command's output is non-empty, the host has commits not yet
on your primary remote — run the bundle workflow before starting new work,
so a later fast-forward pull isn't blocked by divergence.

---

## End-of-session untracked-file audit

Ad hoc scripts written directly on the deploy host (forensics, incident
debugging, manual probes) that are never committed accumulate as untracked
files. They silently block a future `git pull --ff-only` on that host with
an error like:

```
error: The following untracked working tree files would be overwritten by merge:
        <path>
Please move or remove them before you merge.
```

**Why:** an untracked file with the same path as an incoming change is
ambiguous to git — it won't overwrite it automatically, and won't tell you
in advance either; you find out at pull time, usually when you're trying to
do something else entirely. Every prior workaround for this class of
failure (force-clobbering the pull, or skipping the merge check) is worse
than just not leaving the file behind.

**How to apply — before leaving any deploy-host session:**

```bash
ssh <DEPLOY_USER>@<DEPLOY_HOST> 'cd <APP_DIR> && git status --short'
```

For each untracked file:
- **(a) The file is valuable** → copy it to your local machine, open a PR
  with it, then remove it from the host.
- **(b) The file is debug-only** → `ssh <DEPLOY_USER>@<DEPLOY_HOST> 'rm
  <APP_DIR>/<path>'`.

Never leave an untracked file behind for the next session to step on.


---


# Module: CI Gate Governance

**Include this module if:** your CI gate surface is defined across **more
than one coupled file** — e.g. a local-CI runner script that developers run
before pushing, a CI workflow/pipeline config file that runs on the server,
and (optionally) a parity-checking script that cross-validates the two
agree. If your entire CI gate set lives in exactly one file, this module's
structural fix is unnecessary — the single-file case can't silently drop a
gate from "the other copy," because there is no other copy.

This module is the structural fix referenced by CORE.md's "Gate-collapse
prevention" section — read that section first for the failure mode this
addresses.

---

## The failure mode this prevents

When your gate set is defined in N ≥ 2 coupled files, two branches that each
independently edit those files can merge in a way where the **second**
merge silently drops a gate the **first** merge added — because the second
branch was based on a pre-merge version of the shared region, and a naive
rebase/merge resolution can overwrite rather than union the changes. A
parity checker that only confirms "file A and file B agree with each other"
stays green even if both lost the same gate simultaneously; it proves
internal consistency, not completeness against history.

---

## The structural fix: a single source-of-truth `gates.yml`

Instead of each surface defining its own copy of "which gates exist,"
define the gate set **once**, in one file, and have every other surface
either read from it directly or be validated against it.

```yaml
# gates.yml — single source of truth for the CI gate surface
gates:
  - name: lint
    description: Static analysis / style check
  - name: unit-tests
    description: Fast unit test suite
  - name: type-check
    description: Static type checking
  # ... one entry per gate, added here first before anywhere else
```

Then:
- Your local-CI runner script iterates `gates.yml` to know what to run,
  rather than hardcoding a parallel list.
- Your CI workflow config either generates its job list from `gates.yml` at
  config-generation time, or is validated against it by a guard script (see
  below) if your CI system doesn't support dynamic generation.
- Any allowlist for an intentionally-removed gate lives in `gates.yml`
  itself (or a file it references), with a required justification line —
  never a silent deletion.

---

## The guard script

Whatever your CI gate set's actual mechanism, add a guard check that:

1. Diffs the **set of gate names** present on the current branch against
   the set present on the remote default branch (not just diffing file
   contents — diffing the *semantic gate set*, so a gate that got renamed
   out of existence, or removed from one surface but not another, is
   caught).
2. **Fails** if any gate present on the default branch is missing on the
   current branch, unless it's listed in an explicit allowlist file with a
   justification line (and ideally an expiry date, after which the guard
   fails again until the entry is renewed or the removal is made
   permanent by deleting the gate from `gates.yml` properly).
3. Runs as its own CI job/gate — so the very mechanism that could
   accidentally get deleted is itself protected by a check that would need
   to be deleted too (raising the bar from "silent" to "you'd have to
   delete the guard and notice you were doing it").

---

## Process discipline this doesn't replace

Even with `gates.yml` and a guard script in place, when you edit any part of
the gate-definition surface (especially rebasing a branch that was cut
before another gate-adding change merged), manually confirm — after the
rebase — that both the gate you're adding and every pre-existing gate
survive. The guard script catches the mistake before merge; it doesn't
prevent the moment of confusion during a messy rebase from happening in the
first place. Treat the guard as a safety net, not a reason to stop paying
attention during the rebase itself.

To remove a gate **on purpose**, add a justified entry to the allowlist —
never just delete the `run_check`/job/mapping-entry trio directly. For a
**temporary** removal, tag the reason with an expiry date so the guard
starts failing again after that date unless the entry is explicitly
renewed, and prune the entry once whatever it was waiting on has landed.
