#!/usr/bin/env python3
"""gen_ci.py - generate the local CI runner section and the GitHub Actions
workflow job section from a single declarative gates.yml.

WHY THIS EXISTS
----------------
Historically a project like this maintained THREE independently hand-edited
surfaces that had to agree by convention: a local CI runner script (one
run_check invocation per gate), a GitHub Actions workflow file (one job block
per gate), and a parity checker (a dict mapping gate names to job names). Two
PRs touching all three files concurrently could silently drop one PR's gate on
merge/rebase, and nothing caught it until a dedicated deletion-guard script ran.

This script makes that drift class structurally impossible for the *shape* of
the two output surfaces: gates.yml is the ONE place a gate is declared, and
this script deterministically regenerates the corresponding local-runner and
CI-workflow sections. Only the residual, much smaller concerns remain:
  - check_gate_semantic_drift.py: for the handful of gates whose ci_command
    legitimately differs from command, prove local test coverage is a
    superset of CI's.
  - check_gate_deletion.py: catch a gate silently vanishing from gates.yml
    itself across a merge/rebase (the single remaining surface).

MARKER-DELIMITED REGIONS
------------------------
Both output files are written ONLY between a BEGIN/END marker pair. Everything
outside the markers is preserved byte-for-byte, so a project's own
hand-authored preamble (checkout steps, path filters, concurrency blocks, a
`run_check` shell function definition, permissions blocks, etc.) survives
untouched across regenerations.

FIRST-TIME BOOTSTRAP
---------------------
This script does NOT create a local-ci.sh or ci.yml from nothing - a project
must have SOME existing scaffolding first:
  - local-ci.sh: needs a shebang and (conventionally) a `run_check` shell
    function defined above the marker region. If the target file does not
    exist at all, an empty one with a shebang and the markers is created.
  - ci.yml: needs a valid GitHub Actions document with a top-level `jobs:`
    key. If the target file does not exist at all, a minimal valid workflow
    (name/on/jobs) is created with the markers nested under `jobs:`.
If the target file EXISTS but has no markers yet, this script inserts the
marker pair (at the end of the file for local-ci.sh; as the last mapping
entries under the `jobs:` key, appended in text form, for ci.yml) on the first
run. Subsequent runs update only the marked region.

USAGE
-----
    python gen_ci.py --gates gates.yml --local-ci-out local_ci.sh \\
        --ci-yml-out ci.yml --check
    python gen_ci.py --gates gates.yml --local-ci-out local_ci.sh \\
        --ci-yml-out ci.yml --write

--check regenerates in memory and diffs against the committed marked region;
exits 1 with a unified diff on any mismatch, 0 silently on match.
--write regenerates and writes both files in place. Idempotent: running
--write twice produces byte-identical output the second time.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import shlex
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    raise

try:
    import jsonschema
except ImportError:  # pragma: no cover
    print("ERROR: jsonschema is required. Install with: pip install jsonschema", file=sys.stderr)
    raise


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SCHEMA_PATH = SCRIPT_DIR / "gates.schema.json"

LOCAL_BEGIN = "# === BEGIN GENERATED GATES (generated by gen_ci.py --write; do not hand-edit below) ==="
LOCAL_END = "# === END GENERATED GATES ==="

CI_BEGIN = "# === BEGIN GENERATED GATES (generated by gen_ci.py --write; do not hand-edit below) ==="
CI_END = "# === END GENERATED GATES ==="

JOB_ID_SANITIZE_RE = re.compile(r"[^a-zA-Z0-9_-]")


# --------------------------------------------------------------------------
# Loading & validation
# --------------------------------------------------------------------------

class GatesValidationError(Exception):
    """Raised with a human-readable, exact validation error message."""


def load_schema(schema_path: Path) -> dict:
    with open(schema_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_gates(gates_path: Path, schema_path: Path = DEFAULT_SCHEMA_PATH) -> dict:
    """Load gates.yml, validate against the JSON Schema, then apply the
    additional cross-field / cross-array checks the schema cannot express:
      - unique gate names
      - no orphan sibling_test_gate references
      - at least one of allow_local/allow_ci true (after defaults applied)
    Raises GatesValidationError with the exact failure on any problem.
    """
    if not gates_path.exists():
        raise GatesValidationError(f"gates file not found: {gates_path}")

    with open(gates_path, "r", encoding="utf-8") as f:
        try:
            doc = yaml.safe_load(f)
        except yaml.YAMLError as e:
            raise GatesValidationError(f"YAML parse error in {gates_path}: {e}")

    if doc is None:
        raise GatesValidationError(f"{gates_path} is empty")

    schema = load_schema(schema_path)
    validator_cls = jsonschema.validators.validator_for(schema)
    validator_cls.check_schema(schema)
    validator = validator_cls(schema)
    errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.path))
    if errors:
        first = errors[0]
        loc = "/".join(str(p) for p in first.path) or "<root>"
        raise GatesValidationError(
            f"schema validation failed at '{loc}': {first.message}"
        )

    gates = doc.get("gates", [])

    # Apply defaults explicitly so downstream code (and the anyOf-equivalent
    # check below) always sees concrete booleans.
    for g in gates:
        g.setdefault("allow_local", True)
        g.setdefault("allow_ci", True)
        g.setdefault("non_pytest", False)
        g.setdefault("requires", [])

    # Unique names
    names = [g["name"] for g in gates]
    seen = set()
    dupes = set()
    for n in names:
        if n in seen:
            dupes.add(n)
        seen.add(n)
    if dupes:
        raise GatesValidationError(
            f"duplicate gate name(s): {', '.join(sorted(dupes))} - gate names must be unique"
        )

    # At least one of allow_local/allow_ci true
    for g in gates:
        if not g["allow_local"] and not g["allow_ci"]:
            raise GatesValidationError(
                f"gate '{g['name']}' has both allow_local=false and allow_ci=false - "
                "a gate must be runnable somewhere (set at least one to true)"
            )

    # No orphan sibling_test_gate references
    name_set = set(names)
    for g in gates:
        sib = g.get("sibling_test_gate")
        if sib is not None and sib not in name_set:
            raise GatesValidationError(
                f"gate '{g['name']}' has sibling_test_gate='{sib}' which does not "
                f"match any declared gate name. Known gates: {', '.join(sorted(name_set))}"
            )

    return doc


# --------------------------------------------------------------------------
# Local CI runner generation
# --------------------------------------------------------------------------

def _requires_guard(tool: str) -> str:
    return (
        f'command -v {shlex.quote(tool)} >/dev/null 2>&1 || '
        f'{{ echo "SKIP: {tool} not found on PATH"; exit 0; }}'
    )


def _render_local_command_block(gate: dict) -> str:
    """Render the shell fragment that runs this gate's command, wrapping
    multi-line commands in a bash -c block with correct quote escaping, and
    prefixing any `requires` guards.
    """
    command = gate["command"]
    requires = gate.get("requires", [])
    lines: list[str] = []

    for tool in requires:
        lines.append(f"  {_requires_guard(tool)}")

    is_multiline = "\n" in command.strip("\n")
    if is_multiline:
        # Wrap in bash -c '...' with single-quote escaping: replace each `'`
        # with the standard '\'' sequence (close quote, escaped quote, reopen).
        escaped = command.replace("'", "'\\''")
        lines.append(f"  bash -c '{escaped}'")
    else:
        lines.append(f"  {command}")

    return "\n".join(lines)


def generate_local_section(gates: list[dict]) -> str:
    """Generate the body between the local markers: one run_check invocation
    block per gate with allow_local true, grouped/commented by `group`.
    """
    out: list[str] = []
    current_group = None
    for gate in gates:
        if not gate["allow_local"]:
            continue
        group = gate.get("group")
        if group != current_group:
            out.append("")
            out.append(f"# --- group: {group or '(ungrouped)'} ---")
            current_group = group

        out.append("")
        out.append(f"# gate: {gate['name']}")
        out.append(f"# {gate['description']}")
        out.append(f'run_check "{gate["name"]}" \\')
        body = _render_local_command_block(gate)
        out.append(body)

    text = "\n".join(out).strip("\n")
    return text + "\n" if text else ""


# --------------------------------------------------------------------------
# CI workflow generation
# --------------------------------------------------------------------------

def sanitize_job_id(name: str) -> str:
    """Sanitize a gate name to a valid GitHub Actions job-id character set
    (alphanumeric, -, _; must not start with a number per GH's own rules,
    though we keep this permissive and just ensure legal characters)."""
    sanitized = JOB_ID_SANITIZE_RE.sub("-", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = f"gate-{sanitized}"
    return sanitized


def _yaml_str_block(value: str, indent: int) -> str:
    """Render a multi-line string as a YAML literal block scalar (|) at the
    given indent level, otherwise as a plain quoted scalar."""
    pad = " " * indent
    if "\n" in value.strip("\n"):
        lines = value.rstrip("\n").split("\n")
        rendered = "|\n" + "\n".join(f"{pad}  {ln}" for ln in lines)
        return rendered
    return json.dumps(value)  # safe single-line YAML-compatible quoting


def generate_ci_section(gates: list[dict]) -> str:
    """Generate the body between the CI markers: one job block per gate with
    allow_ci true, keyed by the sanitized gate name, with extra_yaml merged in.
    """
    out: list[str] = []
    for gate in gates:
        if not gate["allow_ci"]:
            continue
        job_id = sanitize_job_id(gate["name"])
        ci_command = gate.get("ci_command") or gate["command"]

        out.append(f"  {job_id}:")
        out.append(f"    name: {json.dumps(gate['description'])}")
        out.append("    runs-on: ubuntu-latest")

        requires = gate.get("requires", [])
        if requires:
            out.append(f"    # requires: {', '.join(requires)}")

        # extra_yaml is merged in verbatim as additional top-level keys of
        # this job mapping (e.g. services:, env:, strategy:). It is inserted
        # BEFORE steps so `steps:` remains the last, most-visible key.
        extra_yaml = gate.get("extra_yaml")
        if extra_yaml:
            for line in extra_yaml.rstrip("\n").split("\n"):
                out.append(f"    {line}" if line.strip() else "")

        out.append("    steps:")
        out.append("      - uses: actions/checkout@v4")
        out.append(f"      - name: Run {job_id}")
        out.append(f"        run: {_yaml_str_block(ci_command, 8)}")
        out.append("")

    text = "\n".join(out).rstrip("\n")
    return text + "\n" if text else ""


# --------------------------------------------------------------------------
# Marker-delimited file surgery
# --------------------------------------------------------------------------

def _split_on_markers(existing_text: str, begin: str, end: str) -> tuple[str, str] | None:
    """Return (before, after) surrounding text if both markers are present in
    order, else None.

    The single newline immediately following the END marker (if any) is
    considered part of the marker line's own line-terminator, not part of
    `after` - stripping exactly one here keeps re-splitting an
    already-generated file idempotent (otherwise each write/read/write cycle
    would accumulate one more trailing blank line, since the renderer always
    re-adds a newline after END when composing the block)."""
    if begin not in existing_text or end not in existing_text:
        return None
    begin_idx = existing_text.index(begin)
    end_idx = existing_text.index(end, begin_idx)
    if end_idx < begin_idx:
        return None
    before = existing_text[:begin_idx]
    after = existing_text[end_idx + len(end):]
    if after.startswith("\n"):
        after = after[1:]
    return before, after


def render_local_file(existing_text: str, generated_body: str) -> str:
    split = _split_on_markers(existing_text, LOCAL_BEGIN, LOCAL_END)
    if split is None:
        # Bootstrap: no markers yet. Insert at end of file.
        before = existing_text
        if before and not before.endswith("\n"):
            before += "\n"
        after = ""
    else:
        before, after = split

    if before and not before.endswith("\n"):
        before += "\n"
    if after and not after.startswith("\n"):
        after = "\n" + after

    middle = generated_body.strip("\n")
    block = f"{before}{LOCAL_BEGIN}\n{middle}\n{LOCAL_END}{after}"
    return block


def render_ci_file(existing_text: str, generated_body: str) -> str:
    split = _split_on_markers(existing_text, CI_BEGIN, CI_END)
    if split is None:
        if existing_text.strip() == "":
            # Bootstrap a minimal valid workflow with a jobs: key.
            before = "name: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\njobs:\n"
        else:
            before = existing_text
            if not before.endswith("\n"):
                before += "\n"
            if "jobs:" not in before:
                # Best-effort bootstrap: add a jobs: key at the end.
                before += "jobs:\n"
        after = ""
    else:
        before, after = split

    if before and not before.endswith("\n"):
        before += "\n"
    if after and not after.startswith("\n"):
        after = "\n" + after

    middle = generated_body.rstrip("\n")
    block = f"{before}{CI_BEGIN}\n{middle}\n{CI_END}\n{after}"
    return block


# --------------------------------------------------------------------------
# Diff helpers for --check
# --------------------------------------------------------------------------

def _extract_marked_region(text: str, begin: str, end: str) -> str | None:
    split = _split_on_markers(text, begin, end)
    if split is None:
        return None
    begin_idx = text.index(begin)
    end_idx = text.index(end, begin_idx) + len(end)
    return text[begin_idx:end_idx]


def unified_diff(a: str, b: str, a_name: str, b_name: str) -> str:
    return "".join(
        difflib.unified_diff(
            a.splitlines(keepends=True),
            b.splitlines(keepends=True),
            fromfile=a_name,
            tofile=b_name,
        )
    )


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate local CI runner + GitHub Actions job sections from gates.yml"
    )
    parser.add_argument("--gates", required=True, type=Path, help="Path to gates.yml")
    parser.add_argument("--local-ci-out", required=True, type=Path, help="Path to local CI runner script")
    parser.add_argument("--ci-yml-out", required=True, type=Path, help="Path to GitHub Actions workflow yml")
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA_PATH, help="Path to gates.schema.json")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Diff-only; exit 1 on mismatch")
    mode.add_argument("--write", action="store_true", help="Regenerate and write in place")
    args = parser.parse_args(argv)

    try:
        doc = load_gates(args.gates, args.schema)
    except GatesValidationError as e:
        print(f"GATES_VALIDATION_ERROR: {e}", file=sys.stderr)
        return 1

    gates = doc.get("gates", [])

    local_body = generate_local_section(gates)
    ci_body = generate_ci_section(gates)

    local_existing = args.local_ci_out.read_text(encoding="utf-8") if args.local_ci_out.exists() else ""
    ci_existing = args.ci_yml_out.read_text(encoding="utf-8") if args.ci_yml_out.exists() else ""

    new_local_text = render_local_file(local_existing, local_body)
    new_ci_text = render_ci_file(ci_existing, ci_body)

    if args.write:
        args.local_ci_out.parent.mkdir(parents=True, exist_ok=True)
        args.ci_yml_out.parent.mkdir(parents=True, exist_ok=True)
        args.local_ci_out.write_text(new_local_text, encoding="utf-8", newline="\n")
        args.ci_yml_out.write_text(new_ci_text, encoding="utf-8", newline="\n")
        print(f"wrote {args.local_ci_out}")
        print(f"wrote {args.ci_yml_out}")
        return 0

    # --check mode: compare only the marked region (if present) or the whole
    # generated file (if the target didn't exist / had no markers yet - in
    # that case ANY existing content differing from the bootstrap is a mismatch).
    mismatches = []

    old_local_marked = _extract_marked_region(local_existing, LOCAL_BEGIN, LOCAL_END)
    new_local_marked = _extract_marked_region(new_local_text, LOCAL_BEGIN, LOCAL_END)
    if old_local_marked != new_local_marked or not args.local_ci_out.exists():
        diff = unified_diff(
            local_existing, new_local_text,
            str(args.local_ci_out) + " (committed)",
            str(args.local_ci_out) + " (generated)",
        )
        mismatches.append(("local-ci-out", diff))

    old_ci_marked = _extract_marked_region(ci_existing, CI_BEGIN, CI_END)
    new_ci_marked = _extract_marked_region(new_ci_text, CI_BEGIN, CI_END)
    if old_ci_marked != new_ci_marked or not args.ci_yml_out.exists():
        diff = unified_diff(
            ci_existing, new_ci_text,
            str(args.ci_yml_out) + " (committed)",
            str(args.ci_yml_out) + " (generated)",
        )
        mismatches.append(("ci-yml-out", diff))

    if mismatches:
        print("GATE_CODEGEN_DRIFT: generated output does not match committed file(s).", file=sys.stderr)
        for label, diff in mismatches:
            print(f"\n--- {label} ---", file=sys.stderr)
            print(diff, file=sys.stderr)
        print(
            "\nRun: python gen_ci.py --gates {} --local-ci-out {} --ci-yml-out {} --write"
            .format(args.gates, args.local_ci_out, args.ci_yml_out),
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
